# This workflow uses actions that are not certified by GitHub.
# SÃ£o fornecidas por terceiros e regidas por
# termos de serviÃ§o, polÃ­tica de privacidade e suporte separados
# documentaÃ§Ã£o.

name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: ["main"]

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:

  vars:
    name: Setup Environment ğŸ› ï¸
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - id: vars
        run: |
          if [[ ! "$GITHUB_REF" =~ refs/tags ]]; then
            echo "::set-output name=tag::$(echo $GITHUB_SHA | cut -c 1-8)"
          else
            echo "::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3)"
          fi
      - run: echo "${{ steps.vars.outputs.tag }}"

  # test:
  #   name: Test Application ğŸ”
  #   runs-on: ubuntu-latest
  #   needs:
  #     - vars
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: yarn tsc

  sonarqube:
    name: SonarQube Scan ğŸ”
    runs-on: ubuntu-latest
    needs:
      - vars
      # - test
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v3
    - name: SonarQube Scan ğŸ”
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}

  build-and-push:
    name: Build and Push ğŸ“¦
    runs-on: ubuntu-latest
    needs:
      - vars
      # - test
      - sonarqube
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Set rev.txt ğŸ› ï¸
        run: git show -s --format="%ai %H %s %aN" HEAD > rev.txt

      - name: Set up QEMU ğŸ› ï¸
        uses: docker/setup-qemu-action@@v2.1.0

      - name: Set up Docker Buildx ğŸ› ï¸
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login Docker Registry ğŸªª
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # - name: Build and Push Docker ğŸš€
      #   run: |
      #     cd app/
      #     #yarn add --cwd packages/app @backstage/plugin-kubernetes @backstage/plugin-search @backstage/plugin-search-react @backstage/plugin-catalog
      #     #yarn install --frozen-lockfile
      #     #yarn tsc
      #     yarn build
      #     docker image build . -f packages/backend/Dockerfile --tag diegoluisi/backstage:${{ needs.vars.outputs.tag }}
      #     docker push diegoluisi/backstage:${{ needs.vars.outputs.tag }}

      - name: Build and Push Docker ğŸš€
        uses: docker/build-push-action@v3
        with:
          push: true
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
          tags: ghcr.io/devxp-tech/backstage:${{ needs.vars.outputs.tag }},ghcr.io/devxp-tech/backstage:latest

  trivy:
    name: Trivy Scan ğŸ”’
    runs-on: ubuntu-latest
    needs:
      - vars
      # - test
      - sonarqube
      - build-and-push
    steps:
      - name: Run Trivy vulnerability scanner ğŸ”
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/devxp-tech/backstage:${{ needs.vars.outputs.tag }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security Tab ğŸ“ˆ
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  deploy:
    name: GitOps Deploy ğŸ—ï¸
    runs-on: ubuntu-latest
    needs:
      - vars
      - sonarqube
      - build-and-push
      - trivy

    steps:
    - name: Set Kustomize ğŸ› ï¸
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.9.4"

    - name: GitOps Checkout ğŸ›ï¸
      run: |
        git clone https://${{ secrets.ACCESS_TOKEN_GITHUB }}@github.com/devxp-tech/gitops
        cd gitops
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Update Docker Image Tag âœ¨
      run: |
        cd gitops/apps/backstage/base
        OLD_TAG=$(cat kustomization.yaml | grep 'tag:' |  awk '{print $2}')
        NEW_TAG=${{ needs.vars.outputs.tag }}
        # kustomize edit set image diegoluisi/backstage:${{ needs.vars.outputs.tag }}
        sed -i "s|$OLD_TAG|$NEW_TAG|g" kustomization.yaml

    - name: Commit and Push ğŸš€
      run: |
        cd gitops/
        git commit -am ":robot: [GitHub Action] Set new image tag to https://github.com/devxp-tech/backstage/commit/${{ needs.vars.outputs.tag }}"
        git push

  slack-workflow-status:
    if: always()
    name: Post Status To Slack  ğŸ“£
    needs:
      - vars
      - sonarqube
      - build-and-push
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          # Optional Input
          channel: 'github-notifications'
          name: 'github-notifications'
          # icon_emoji: ':poop:'
          icon_url: '${{ secrets.SLACK_ICON }}'
