# This workflow uses actions that are not certified by GitHub.
# SÃ£o fornecidas por terceiros e regidas por
# termos de serviÃ§o, polÃ­tica de privacidade e suporte separados
# documentaÃ§Ã£o.

name: main

on:
  push:
    branches: [ main ]

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  vars:
    name: Setup Environment ğŸ› ï¸
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - id: vars
        run: |
          if [[ ! "$GITHUB_REF" =~ refs/tags ]]; then
            echo "::set-output name=tag::$(echo $GITHUB_SHA | cut -c 1-8)"
          else
            echo "::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3)"
          fi
      - run: echo "${{ steps.vars.outputs.tag }}"

  sonarqube:
    name: SonarQube Scan ğŸ”
    runs-on: ubuntu-latest
    needs:
      - vars
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan ğŸ”
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}

  build-and-push:
    name: Push Docker Image ğŸ“¦
    runs-on: ubuntu-latest
    needs:
      - vars
      # - sonarqube
    steps:
      - name: Check out the repo ğŸ› ï¸
        uses: actions/checkout@v3

      - name: Log in to Docker Hub ğŸªª
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker ğŸš€
        run: |
          cd app/
          yarn add --cwd packages/app @backstage/plugin-kubernetes @backstage/plugin-search @backstage/plugin-search-react @backstage/plugin-catalog
          yarn install --frozen-lockfile
          yarn tsc
          yarn build
          docker image build . -f packages/backend/Dockerfile --tag diegoluisi/backstage:${{ needs.vars.outputs.tag }}
          docker push diegoluisi/backstage:${{ needs.vars.outputs.tag }}

  deploy:
    name: GitOps Deploy ğŸ—ï¸
    runs-on: ubuntu-latest
    needs:
      - vars
      - sonarqube
      - build-and-push

    steps:
    - name: Set Kustomize ğŸ› ï¸
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.9.4"

    - name: Git Checkout ğŸ›ï¸
      run: |
        git clone https://${{ secrets.ACCESS_TOKEN_GITHUB }}@github.com/devxp-tech/gitops
        cd gitops
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Update Docker Image Tag âœ¨
      run: |
        cd gitops/apps/backstage/base
        OLD_TAG=$(cat kustomization.yaml | grep 'tag:' |  awk '{print $2}')
        NEW_TAG=${{ needs.vars.outputs.tag }}
        echo "Change tag $OLD_TAG  to $NEW_TAG"
        # kustomize edit set image diegoluisi/backstage:${{ needs.vars.outputs.tag }}
        sed -i "s|$OLD_TAG|$NEW_TAG|g" kustomization.yaml
        cat kustomization.yaml | grep 'tag:' |  awk '{print $2}'

    - name: Commit and Push ğŸš€
      run: |
        cd gitops/
        git commit -am ":robot: [GitHub Action] Set new image tag to https://github.com/devxp-tech/backstage/commit/${{ needs.vars.outputs.tag }}"
        git push

  slack-workflow-status:
    if: always()
    name: Post Status To Slack  ğŸ“£
    needs:
      - vars
      - sonarqube
      - build-and-push
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          # Optional Input
          channel: 'github-notifications'
          name: 'github-notifications'
          # icon_emoji: ':poop:'
          icon_url: '${{ secrets.SLACK_ICON }}'
