name: techdocs

on:
  push:
    paths:
      - "docs/**"
      - "mkdocs.yml"

jobs:
  env:
    uses: devxp-tech/.github/.github/workflows/env.yaml@main

  docs:
    uses: devxp-tech/.github/.github/workflows/techdocs.yaml@main
    secrets: inherit
    with:
      repository: ${{ needs.env.outputs.repository }}
    needs:
      - env
